spring.application.name=uprzejmie-donosze

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=UPRZEJMIE
spring.datasource.password=haslo
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.thymeleaf.cache=false

app.admin.username=admin
app.admin.password=admin123
app.admin.first-name=Administrator
app.admin.last-name=Systemu